version: '3.9'

services:
  redis:
    hostname: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PORT: 6379

  # app:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
